[package]
name = "substreams-uniswap-v3"
version = "0.1.0"
description = "Uniswap v3 Substreams"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ethabi = "17.0"
wasm-bindgen = "0.2.79"
prost = "0.11.0"
prost-types = "0.11.0"
hex = "0.4.3"
substreams = "~0.0.20"
substreams-ethereum = "0.2.2-rc.2"
num-bigint = "0.4"
bigdecimal = "0.3"
pad = "0.1"

# Have to use this version because the recent onces redefine
# a alloc and wealloc which breaks wasm memory management
base64 = "0.13.0"

[build-dependencies]
prost-build = "0.11.0"
anyhow = "1"
substreams-ethereum = "0.2.2-rc.2"
