[package]
name = "substreams-uniswap-v3"
version = "0.1.0"
description = "Uniswap v3 Substreams"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ethabi = "17.0"
wasm-bindgen = "0.2.79"
prost = { version = "0.10.1" }
prost-types = "0.10.1"
hex = "0.4.3"
substreams = { git = "https://github.com/streamingfast/substreams/", branch = "develop"  }
substreams-ethereum = { git = "https://github.com/streamingfast/substreams-ethereum", branch = "feature/num_big_int_type" }
num-bigint = "0.4"
bigdecimal = "0.3"
pad = "0.1"

[build-dependencies]
prost-build = "0.10.1"
anyhow = "1"
substreams-ethereum = { git = "https://github.com/streamingfast/substreams-ethereum", branch = "feature/num_big_int_type" }
